### PR TITLE
Add Bazel build tool to image

### PR DESCRIPTION
**Pull request by philomather**

### CODE REVIEW

**Comment by sweoggy** [comment]
@philomather build failed with:

```
Get:24 http://deb.debian.org/debian buster/main amd64 python3-pkg-resources all 40.8.0-1 [153 kB]
[91mE: Failed to fetch http://deb.debian.org/debian/pool/main/p/python3.7/libpython3.7_3.7.3-2_amd64.deb 404 Not Found [IP: 151.101.250.133 80]
E: Failed to fetch http://deb.debian.org/debian/pool/main/p/python3.7/libpython3.7-dev_3.7.3-2_amd64.deb 404 Not Found [IP: 151.101.250.133 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
[0m
```

Did you try to build it locally?

**Comment by philomather** [comment]
> @philomather build failed with:
> 
> ```
> Get:24 http://deb.debian.org/debian buster/main amd64 python3-pkg-resources all 40.8.0-1 [153 kB]
> �[91mE: Failed to fetch http://deb.debian.org/debian/pool/main/p/python3.7/libpython3.7_3.7.3-2_amd64.deb 404 Not Found [IP: 151.101.250.133 80]
> E: Failed to fetch http://deb.debian.org/debian/pool/main/p/python3.7/libpython3.7-dev_3.7.3-2_amd64.deb 404 Not Found [IP: 151.101.250.133 80]
> E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
> �[0m
> ```
> 
> Did you try to build it locally?

Yep, I built it and tested out using bazel commands in the container; it was all fine locally.

**Comment by sweoggy** [comment]
@philomather Try to re-push it (add a newline or something). I can't seem to re-trigger the dockercloud build

**Comment by philomather** [comment]
@sweoggy There you go

**Pull request merged**
